### ISSUE TITLE
Pulled from integration list ?

### ISSUE THREAD

**Issue by mrlightbulb** [filipvh/hass-nhc2#10]
Hi,

NIko home control 2 is not searchable anymore in the integration list.
is this project been deleted / ended ?

**Comment by filipvh** [comment]
Hi, how did you add it to your integrations?
It's a custom component you add manually or using HACS.

**Comment by mrlightbulb** [comment]
Hi,

My AutoAssistant is a virtual appliance ( using a ova file from AutoAssitant ) 
followed up the setup procedure and tried to search for niko home control in the integration list but wasn't there
I tried a docker version before too but it had the exact same issue.


But it is a custome component prop not compatible with the closed appliance version / docker version ?

**Comment by filipvh** [comment]
AutoAssistant? I do not know what you are talking about.

**Comment by mrlightbulb** [comment]
> Hi, how did you add it to your integrations?
> It's a custom component you add manually or using HACS.

I got HACS installed .
But still cant find the niko home control in the repositories

**Comment by mrlightbulb** [comment]
It's solved. wrong version was used
