### ISSUE TITLE
Switch seen as Lights

### ISSUE THREAD

**Issue by mrlightbulb** [filipvh/hass-nhc2#11]
Hi,

Under NHC2 I have an "other switchable device" configured 

![Screenshot 2020-12-21 at 15 52 05](https://user-images.githubusercontent.com/2939318/102790018-3141e900-43a5-11eb-95a6-a8f659a5757a.png)

When I first set up the NHC2 integration it asks if I wanted to import switchable devices as Lights.
I explicitly didn't want to configure that and leave it unchecked.

![Screenshot 2020-12-21 at 15 48 43](https://user-images.githubusercontent.com/2939318/102790043-3737ca00-43a5-11eb-8775-62bfd58611b6.png)

But still, it imports my "other switchable " device types from NHC2 as a Light into AutoAssistant.

- How can I solve this?
- Do i use the wrong type in nhc2 ?
- should I completely delete all NHC2 configs in autoassistant ?

Thnx

**Comment by filipvh** [comment]
I have not yes used 'other switched devices'
![image](https://user-images.githubusercontent.com/6095002/102792854-56d0f180-43a9-11eb-803e-eef469bcbad3.png)
Normally only lights and dimmers should become lights in this case.
If I omit the 'Import switched as lights' options, i get something like this
![image](https://user-images.githubusercontent.com/6095002/102793050-9d265080-43a9-11eb-90ed-2206119779f7.png)
But these are not 'other switched devices'
We would have to investigate you devices list
Do you have experience with mqtt.fx or an other mqtt client?

**Comment by mrlightbulb** [comment]
Apparently, old config must have been nested inside.
even when requesting updates from NHC2 it didn change

Fixed by doing so : remove of the integration >> reboot autoassistant >> install nhc 2 integration >> reboot again.
now the other switchable device is a device.

Too bad, we can't override the type as I rather liked to be seen as a lock / door .
I mainly use it to translate it to homekit and then you can do a lot of nice notifications when its a lock / door instead of just a switch. 

Tried Openhab before but openhab has a lot of inverse issues with status fetch from NHC2 to HomeKit
never encountered that in this here very good job !

**Comment by filipvh** [comment]
So if this is a link to your garage door opener, you could wrap it in a cover entity.
But for this you would need a different action for UP/DOWN at least.
For a garage door that only has 'one button', I would suggest not using NHC2, but using other solutions.
For this purpose I've built my own solution using a raspberry pi, some sensors and a relay.
A rotary encoder, 2 microswitches and a relay.
A python script taks MQTT with hass, uses the sensors to check/sync state, achieve requested positions with a 1% accuracy, and signal open/close/direction change.
It's not perfect, and requires you to make physical connections between the sensors and the garage door.


If you would be interested, I could provide you with the PCB design I used in combination with a raspberry PI.
beyond receiving my example code and the PCB design, YOU wil have to solder, connect, setup it all.
