### ISSUE TITLE
Fan only supports on/off mode

### ISSUE THREAD

**Issue by SonnyBBQ** [filipvh/hass-nhc2#14]
Think this is more a feature request vs an issue, but would it be possible to include the NHC2 settings for a fan (ventilation)?
low, medium, high, boost

**Comment by filipvh** [comment]
Normally we should support this in the latest version, bu t it's possible, due to a bug, this is broken.
Will try to investigate this next week.

**Comment by SonnyBBQ** [comment]
Thanks, let me know if there is any way I can support.

**Comment by SonnyBBQ** [comment]
Hi Filip,  due to an IP issue, I had to reinstall the NHC integration and it **does** now show the fan speed options for me.  Not sure what went wrong the first time.

Unfortunately, changing the speed doesn't seem to work via Home Assistant (while it does via the NHC app).

**Comment by SonnyBBQ** [comment]
All working fine now
