### ISSUE TITLE
Request for additional Niko device types

### ISSUE THREAD

**Issue by MirandaPoth** [filipvh/hass-nhc2#15]
Hi Filip,
Thanks very much for this integration, I am using it very successfully. 

Please can you add 'alloff' and 'generic' to the list of devices? I think this requires a small change to nhc2-coco to add them to the list of LIST_VALID_SWITCHES. I'm pretty sure they behave the same as switches.

I am happy to help with testing if that would help?

I would make the change myself but I am not familiar with Home Assistant development.
Thanks very much,
Miranda

**Comment by joleys** [comment]
Miranda,

Adding 'alloff' and 'generic' require additional coding, since the control commands and status messages are different for these devices.

Regards,
Jo

**Comment by MirandaPoth** [comment]
Hi Jo,
OK, thanks for that. I guess I was being over-optimistic!
I'll do some work on it myself. 
Cheers,
Miranda

**Comment by filipvh** [comment]
@MirandaPoth @JorisDeRieck has added generic to the underlying nhc2-coco lib.
He was going to add it to this hass integration soon.
The alloff we could take a look after later, however,
I would do this functionality within hass, as then all lights, also non nhc2's will turn off.

**Comment by MirandaPoth** [comment]
@filipvh Thanks for this update, and @JorisDeRieck thanks very much for the changes to nhc2-coco.

I have actually taken a copy of both sets of code and started implementing both generic and alloff. These are implemented in my local version only. I intend to add thermostat and possibly pir and timeschedule too if it's feasible.

@filipvh The reason for wanting alloff implemented is that I have two 'alloff' routines in my Niko system;
1. To turn off all the downstairs lights, but leave the rest on
2. To turn off all lights inside the house and leave one of the lights on for 10 seconds for exitting. 
Neither of these turn off the lights at the front of the house, which are controlled by light level and/or PIR. 
Also, I have tried 'all lights off' in Alexa, and the Niko version is much more satisfactory, as Niko turns all lights off at once, whereas Alexa has to go through each one in turn which takes several seconds. I would not want this behaviour in HA.

So, I don't think putting this functionality within hass-nhc2 would work for me, but I am happy to just retain my local version.
