### ISSUE TITLE
Stuck on connecting..

### ISSUE THREAD

**Issue by lonione** [filipvh/hass-nhc2#2]
Hi filip, thanks for you work!
I've just started experimenting with this and would like to connect a NHC2 to our HA.
I've installed your NHC component by cloning the git directory to /custom_components/nhc2
I've also done a 'pip install nhc2-coco'

I've opted for integration method1, as I'm not sure how to do step2 of Method2.

I've added the following to my configuration.yaml file and setup debug logging for custom components. 
`nhc2:
   host: 10.10.100.64
   port: 8884
   username: 'hobby'
   password: 'mypassword'`

After restart, I only get a single entry in the log file related to NHC2:
DEBUG (MainThread) [custom_components.nhc2] Connecting to 10.10.100.64:8884
 Is there anything I'm missing?

**Comment by filipvh** [comment]
Are you sure 'host' is being interpreted as a string?
I'm not so versed in yaml, so I'm not 100% sure.
Also, not so sure if the code on this repo is my latest one. I'll check...

**Comment by filipvh** [comment]
ok, the version i'm using and the one on this repo are identical.
here's my working config
![image](https://user-images.githubusercontent.com/6095002/72211203-8ef86080-34c7-11ea-9380-49ebdb74730c.png)
the example you show, is the username one obtained from a actual profile, configured locally with the Niko programming tool? You did read the part "How to get the credentials" in the readme?

Also, hate to ask, but you have a Niko Home Control II right? Not the old one?

**Comment by lonione** [comment]
Thanks, the error was on my part - 
I tried connecting using the newly enabled hobby api, which didn't work - but setting up the touchscreen profile did. All is OK now. thanks...
What was puzzling though was the absence of messsages in logfiles despite the "debug" flag set

**Comment by peter-d** [comment]
I am having the same problem - I did look up the credentials via the sqlite db, but also cannot connect, I only see the connecting... message in the logs and then nothing. 

@lonione I also do have the hobby API enabled, but cannot seem to disable it. Did you have to do something special to make it work?

This is my config for nhc2: (with user and passwd from the touch profile as mentioned in the readme)
```yaml
nhc2:
    host: '192.168.10.19'
    port: 8883
    username: !secret nhc2_user
    password: !secret nhc2_password
```

**Comment by lonione** [comment]
I am no longer using HA, so can't really help. So just a general comment - I've noticed my config was using a different port though, 8884... make sure you have your networking right.

**Comment by filipvh** [comment]
@peter-d 
The latest version is much more easy to setup.
If you want, you can join our slack to help with providing feedback more directly
https://join.slack.com/t/nhc2/shared_invite/zt-j6qy16sl-kZF6V__uTCLVLpZUNutJWA
