### ISSUE TITLE
Not available in HASS

### ISSUE THREAD

**Issue by ovanpeve** [filipvh/hass-nhc2#23]
Hi Filip,

I searched for your integration in HASS but didn't find it in the GUI.
Well, I've been redirected to https://www.home-assistant.io/integrations/niko_home_control/ but this doesn't give the way to install it...

Is this project abandoned ?

Thanks !
Olivier.

**Comment by SonnyBBQ** [comment]
Hi Olivier,  you need to install it via HACS first, or add it as a custom component manually.

I suggest the HACS route, since you'll be able to add other custom components more easily in future.
If you don't have HACS installed, you can find instructions here: https://hacs.xyz/

**Comment by ovanpeve** [comment]
Got it working through HACS.
Thanks,
Olivier
