### ISSUE TITLE
New NHC2 update

### ISSUE THREAD

**Issue by anvarit** [filipvh/hass-nhc2#26]
Hi all, as you maybe noticed, Niko has rolled out a mayor update to their NHC2 platform. 
Did some already tested out if the integration is still working with Niko's new release?

**Comment by joleys** [comment]
The biggest changes are related to access control which is not part of the current integration.  I can assure there are no issues with the latest NHC software and the HA integration, as it has been running for multiple weeks without issue in my installation.

**Comment by anvarit** [comment]
Great thanks for the confirmation, time to upgrade then!
