### ISSUE TITLE
1.7.0-beta1 Seems to crash at random moments

### ISSUE THREAD

**Issue by sweebel** [filipvh/hass-nhc2#27]
Currently testing 1.7.0-beta1
After X time (1 day ~ 2 days ) I cannot control through HA;  only restart gets it working again. 

Log:
[20210903-Debug-1.7.0-beta1.txt](https://github.com/filipvh/hass-nhc2/files/7104325/20210903-Debug-1.7.0-beta1.txt)

installation: Clean HA, VM installation with HACS 
NHCII Controller software version: 2.12.1.1535

Any suggestions to find the cause?

**Comment by filipvh** [comment]
If you can, use an MQTT client to manually connect to the controller and inspect the message(s). If you need more help, ask. I hope to have time again by the end of the year to add more debug options to the code...

**Comment by sweebel** [comment]
Ok will do! Currently working my way into the code. Hoping to be usefull for testing / adding features.

**Comment by Gavergracht** [comment]
> 
> 
> If you can, use an MQTT client to manually connect to the controller and inspect the message(s). If you need more help, ask. I hope to have time again by the end of the year to add more debug options to the code...

Hey Filip, kan ik jou op 1 of andere manier vlot bereiken ? Ik krijg home assistant en niko niet in orde. Zie jij het zitten om me even te helpen ?
