### ISSUE TITLE
NHC Videophone (Videobuitenpost NHC)

### ISSUE THREAD

**Issue by KRi570F** [filipvh/hass-nhc2#42]
Videophone integration
- when having NHC Videophone, you can get the camera live feed buy using the ip eg: 192.168.1.3, username: user and the password empty.

it would be cool having this integrated into home assistant, by your module hass-nhc2

**Comment by williammorren** [comment]
you can just add it as a generic camera inside of home assistant.

**Comment by KRi570F** [comment]
Hi,

Thank you for letting me know. I’m almost completely new to Home Assistant.
That generic camera doesn’t help ☹ can you please assist?
IP: 10.27.0.53
Username: user
Password: empty

***@***.***

***@***.***

***@***.***

Thank you in advance

Regards Kristof


Mvg Kristof



Van: ***@***.***>
Verzonden: zondag 3 april 2022 14:43
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [filipvh/hass-nhc2] NHC Videophone (Videobuitenpost NHC) (Issue #42)


you can just add it as a generic camera inside of home assistant.

**Comment by SonnyBBQ** [comment]
Try this by adding a generic camera through the UI ('generic' integration)

Still image: leave blank
Stream source URL: add http://username:password@10.27.0.53:15110/pbhelper/stream.mjpeg?width=720&height=576?quality=80
RTSP transport:tick HTTP
Authentication: basic
Username: user
Password: your password
Verify SSL: untick

Note in the URL, you should update with your username, password and IP.  Leave the port number at 15110

**Comment by jonas87** [comment]
> Try this by adding a generic camera through the UI ('generic' integration)
> 
> Still image: leave blank Stream source URL: add http://username:password@10.27.0.53:15110/pbhelper/stream.mjpeg?width=720&height=576?quality=80 RTSP transport:tick HTTP Authentication: basic Username: user Password: your password Verify SSL: untick
> 
> Note in the URL, you should update with your username, password and IP. Leave the port number at 15110

I can't get this to work. Does this only work for the default user? My username is my email address.
Basically my username and password that work for https://mynikohomecontrol.niko.eu/ do not work for me to set up the camera. I had a similar problem that I could not get the NHC2 hass integration to work through the default user, but it worked through the hobby account. How do you even reset the password for the default account? I can only find instructions to reset the password for the email address linked account.

**Comment by SonnyBBQ** [comment]
The user and password for the camera are different then those of your NHC account.  Default login is user: admin and password: 123qwe

Try accessing your camera first by going to the IP of your NHC installation, followed by port 15110.  So example: http://10.27.0.53:15110
You should then be able to login with the above details.

NOTE - you can change the admin password through the camera link, but then it won't work within your NHC app anymore.
NOTE 2 - When you change the password, it is capped to 14 characters (this is not stated anywhere)

**Comment by thomas-svrts** [comment]
@KRi570F 

did you use http://admin:qwe123@ip..... or did you use your email address? 
not very clear to which password you are referring because the 'generic camera' integration also asks a separate password.
Already tried a lot of variations, in my access control app I use an email address as user.

![image](https://user-images.githubusercontent.com/81048302/181464558-44898038-8442-4927-b0f1-fe78e23a3408.png)

**Comment by SonnyBBQ** [comment]
Hi Thomas,  try a different solution...

add a MJPEG IP camera integration through the UI

Still image: http://10.27.0.53:15110/pbhelper/stream.mjpeg
Stream source URL: http://10.27.0.53:15110/pbhelper/stream.mjpeg
Username: admin
Password: 123qwe
Verify SSL: untick

Note in the URL, you should update with your IP.  If it doesn't work, try removing the port number 15110 from the URL.

**Comment by davidvf** [comment]
Hi all, 

Anyone else noticed that port 15110 is no longer available after upgrading to 2.16?
It worked perfectly with 2.15... I had frigate running on top of the stream to detect persons or cars on my driveway, but that seems no longer possible now.. :(

**Comment by anvarit** [comment]
Can you do a network scan against the IP address to see if the port hasn't changed?
You can use nmap (command line) or if on Windows zenmap 
https://phoenixnap.com/kb/nmap-scan-open-ports

After seeing this I'm not going to upgrade myself as this a integral part in my environment.

**Comment by davidvf** [comment]
Tried to reboot the controller, but no luck…
nmap port scan is also not showing the port anymore :frowning:

Nmap scan report for xxxxx.iot (x.x.x.x)
Host is up (0.00084s latency).
Not shown: 65526 filtered ports
PORT STATE SERVICE
22/tcp open ssh
80/tcp open http
443/tcp open https
3580/tcp open nati-svrloc
4443/tcp open pharos
5060/tcp open sip
5061/tcp open sip-tls
8883/tcp open secure-mqtt
8884/tcp open unknown

**Comment by SonnyBBQ** [comment]
I'm still on 2.15 and an NMAP scan is not showing the 15110 directly.  Try scanning  for the exact port: sudo nmap -p 15110 x.x.x.x

The difference in my ports versus your list is that I don't show the 8883 and 8884.
Could you also try connecting to port 8884 (since tcp open unknown) and see if that gives you access to the camera?

**Comment by davidvf** [comment]
Connecting on 8884 using http gives me `err_connection_reset`. Using https `err_empty_response`

```
Starting Nmap 7.80 ( https://nmap.org ) at 2022-11-09 13:43 CET
Nmap scan report for xxxx.iot (x.x.x.x)
Host is up (0.00059s latency).

PORT      STATE    SERVICE
15110/tcp filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 0.29 seconds
```

**Comment by bccrew** [comment]
![image](https://user-images.githubusercontent.com/8138958/200835110-37defb91-2a8a-4ac2-86c1-55bd37ee6e63.png)

Does this still work? Can you test the mjpeg URL on port 443?

The videophone is in fact a Robin SV

https://support.robintele.com/download_attachment.php?kb_att=306

**Comment by davidvf** [comment]
```
[david@owl:~ $] curl -u admin:xxxxx "http://x.x.x.x/camera/frame.jpeg"
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>
```

**Comment by mherwege** [comment]
> 8883/tcp open secure-mqtt
> 8884/tcp open unknown

8883 is the secure mqtt port used between the controller and the touch panels. 8884 is the secure mqtt port for the hobby api.

If the videophone is in your normal LAN address range, you may still be able to access it directly without the port number (so not the IP of the controller, but of the videophone). But it could be Niko close the port forwarding useful if the videophone is connected directly to the controller.
Honestly, this was a potential security risk. Anyone mistakenly exposing the controller and port would be able to access the camera, as it has default passwords. Changing the password made it impossible to use it in the Niko system.

**Comment by bccrew** [comment]
The videophone is connected directly to one of the ports of the controller right? Does it receive an IP address in a private subnet different from your LAN? I believe it was like that. If you connect a laptop or switch on that port, do they also receive an IP address or is this DHCP server limited to certain mac address prefixes?

I remember that someone attached a 2nd NIC of a synology NAS in the VLAN of the video port of the controller to be able to access the video feed and record directly on his synology

**Comment by davidvf** [comment]
In my case the videophone is indeed directly connected to the controller. So it receives an IP from that controller, which is out of my reach. I haven't tried to connect a laptop to the controller, but i suppose it would probably work. I guess that is how the electrician initially did the programming of the controller before i moved in.

**Comment by bccrew** [comment]
I believe the connected controller does not do NAT to the IP address of the videophone in some way. In other words, you can not reach the subnet from your LAN. What you can try to do is find out which IP address is handed out to your videophone and try to put a switch in between and make a bridge to your LAN.

**Comment by anvarit** [comment]
Correct, the best way to receive the image / videos from the videophone is to put it on a seperate switch. 
As example, my video unit is on a POE switch and gets an IP out of my IoT network.
Then my NVR reads out the videounit through RTSP with the following string rtsp://ip/rtsp/video.av on port 554
The NHC2 controllers finds videounit without any problems

PS: my NVR is BlueIris, that is integrated in HASS

**Comment by slecompt** [comment]
Just a small question to get some insight into the above solution. Does this mean you effectively connect the videophone to the WAN port of the Controller instead of using port 1,2 or 3? I also see that there is an option in the NHC programming software to configure port 3 to connect the Controller to an 'integrated' (IoT) home network, it seems the DHCP function is disabled in that case. I assume that only the switching function is left over in that configuration? Maybe connecting your home network directly (with your own DHCP server) to port 3 also provides the same functionality in that case? I tried this however and I didn't get any new devices visible in my subnet. Maybe the videophone was still using the old subnet and IP it got from the NHC DHCP server...

**Comment by bccrew** [comment]
WAN is only meant for internet connectivity and most likely uplink to your home router or network switch. Port 1, 2 and 3 normally function as an internal network that the NHC Controller uses to communicate with the controller. Although I have never tried it myself, you could try to see if your laptop receives a DHCP address when you hook it up to the port where your videophone is connected. If another port (1-2-3) has the same result, you can reach the video stream that way. Only thing left to do is find a way to integrate that subnet into your own LAN :)

**Comment by slecompt** [comment]
> Correct, the best way to receive the image / videos from the videophone is to put it on a seperate switch. As example, my video unit is on a POE switch and gets an IP out of my IoT network. Then my NVR reads out the videounit through RTSP with the following string rtsp://ip/rtsp/video.av on port 554 The NHC2 controllers finds videounit without any problems
> 
> PS: my NVR is BlueIris, that is integrated in HASS

@anvarit, I assume in your solution the NHC2 controller finds the video unit through the WAN port?

**Comment by davidvf** [comment]
> 

So i have hooked up my homeassistant server with a secondary interface to port 1 of the connected controller. Got an IP in the range 10.69.55.0/24 (port 2 is used for my video unit). The WAN interface is still connected to my LAN switch, otherwise i cannot use the hobby API anymore.

From there i was able to pick up the stream again. FYI port scan on the videophone
```
#nmap 10.69.55.228
Starting Nmap 7.80 ( https://nmap.org ) at 2022-12-15 14:12 CET
Nmap scan report for nikovds.fifthplay.com (10.69.55.228)
Host is up (0.0044s latency).
Not shown: 996 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https
554/tcp open  rtsp
```

connection to the stream is still working as before:
`http://admin:xxx@10.69.55.228/pbhelper/stream.mjpeg`


Glad my frigate setup is up and running again :)

**Comment by raftheunis87** [comment]
> So i have hooked up my homeassistant server with a secondary interface to port 1 of the connected controlle

I'm trying to connect to my outdoor video doorbell using rtsp. I'm currently using VLC to keep it simple.

I did a `nmap` that gave me following results:

~ ❯ nmap 192.168.0.26                                                                                                                                                                                                              15:08:40
Starting Nmap 7.93 ( https://nmap.org ) at 2023-01-24 14:31 CET
Nmap scan report for 192.168.0.26
Host is up (0.0055s latency).
Not shown: 995 closed tcp ports (conn-refused)
PORT     STATE SERVICE
554/tcp  open  rtsp
6666/tcp open  irc
8000/tcp open  http-alt
8200/tcp open  trivnet1
9010/tcp open  sdr

Then I tried to connect to `rtsp://192.168.0.26:554` in VLC and get a prompt for a username and password.
I tried the admin:123qwe combo, but that doesn't seem to work :( Anyone else knows where I can get the credentials from?

**Comment by raftheunis87** [comment]
@davidvf , Does it still work for you? I'm having this video doorbell btw from Niko: https://www.niko.eu/en/products/door-communication/digital-solutions/video-kit-2-wire-with-access-control-module-external-and-internal-video-unit-productmodel-niko-65aa624b-007c-5e06-8224-a11f834d7233

I just can't get it to work. It keeps prompting for a username and a password.

**Comment by davidvf** [comment]
@raftheunis87, for me it still works.
I have this one: [https://www.niko.eu/en/article/550-22001](https://www.niko.eu/en/article/550-22001)

This is the path i am using for my frigate instance:
`- path: http://admin:123qwe@10.69.55.228/pbhelper/stream.mjpeg?width=1280&height=720`

From hass, i just do the frigate integration and it works flawlessly.
I guess you can try the mjpeg stream like i do.

**Comment by thomas-svrts** [comment]
You have both different video doorbells.
The one @raftheunis87 has doesnt work.

**Comment by threster** [comment]
I have the niko videophone (videobuitenpost) and touchscreen connected to my switch. Connected controller with the WAN port is linked to the same switch. They find each other, no problem.
In this way I can use Synology surveillance station as NVR to do motion detection, and record even if people don't actually ring the bell.

Problem is that after enabling surveillance station, when someone rings the bell and you pick up (either on the niko touchscreen or on mobile phone), the audio is stopped from both sides after about one second. Video on touchscreen or mobile app is fine.
In surveillance station, I get notifications it lost connection to the videophone when someone rings the bell and it reconnects about 2 minutes later.

Having no usable audio in the niko app or touchscreen is a problem for me. Anyone having similar problems, solutions?

**Comment by anvarit** [comment]
Sadly, enough that is known issue.
My installation suffers from the same. The product sets up a VOIP channel to the Niko Cloud system but it seems if you more then one stream running then it suffers from delays.

I didn't find a solution yet.

________________________________

**Comment by flimofly** [comment]
Sorry for reopening this old issue but has anyone had any success in opening the door through Home Assistant?

I have video door station 550-22011 (https://www.niko.eu/en/products/niko-home-control/ip-products/external-video-unit-productmodel-niko-9d1cdb0b-fada-4f48-ac40-1d796d583578) 

In the 2019 API manual for the Robin video door station (https://www.robintele.com/images/downloads/How-To_The_Robin_API_v3.6.0_NL.pdf) there are commands for opening the door:

`curl -u admin:<password> "http://<address>/api/v1/dooropener_open"`

The same action is available via the web interface of the door station.

However, the result of this command is not actually to open the door, like in the Niko Home Control mobile app.  One just hears a short ringtone while the relay is supposed to toggle but the relay does not actually move. 

Could it be that the doorbell was wired wrong? But I would assume that in that case opening the door wouldn't work via the Niko Home Control mobile app either?

**Comment by sennedebie** [comment]
> > 
> 
> So i have hooked up my homeassistant server with a secondary interface to port 1 of the connected controller. Got an IP in the range 10.69.55.0/24 (port 2 is used for my video unit). The WAN interface is still connected to my LAN switch, otherwise i cannot use the hobby API anymore.
> 
> From there i was able to pick up the stream again. FYI port scan on the videophone
> 
> ```
> #nmap 10.69.55.228
> Starting Nmap 7.80 ( https://nmap.org ) at 2022-12-15 14:12 CET
> Nmap scan report for nikovds.fifthplay.com (10.69.55.228)
> Host is up (0.0044s latency).
> Not shown: 996 closed ports
> PORT    STATE SERVICE
> 22/tcp  open  ssh
> 80/tcp  open  http
> 443/tcp open  https
> 554/tcp open  rtsp
> ```
> 
> connection to the stream is still working as before: `http://admin:xxx@10.69.55.228/pbhelper/stream.mjpeg`
> 
> Glad my frigate setup is up and running again :)


Dear davidvf,

Could you give some instructions on how to use the Niko video unit (550-22001) with Frigate/Home Assistant?

Thanks in advance,

Senne

**Comment by flimofly** [comment]
> Could you give some instructions on how to use the Niko video unit (550-22001) with Frigate/Home Assistant?

For Home Assistant I have found that it sometimes matters in which order your do things.

1.  Make sure the video unit works when connected directly to the NHC connected controller and inside the NHC mobile app. 
2. Install the NHC2 integration in Home Assistant and check whether the camera unit is part of the devices
3. Then connect the connected controller to your router and remove the ethernet cable for the video unit from the connected controller, instead plugging that one directly into your router.
4. Log in to your router to find the local IP adres for the camera. You should be able to access the video stream via that IP address (username: user ; password: (empty) or username: admin ; password: 123qwe)
5. Now you should be able to see the video stream in Home Assistant, either as a device in the NHC2 integration or by adding a camera using the IP address.

I haven't used Frigate yet but motion detection is an option when you login to the camera via its local IP address (as admin). 

Note that I have solved some issues with reconnecting (after changing many settings) by resetting the video unit to factory settings via its admin panel.

**Comment by davidvf** [comment]
I left my video unit connected to the controller, like that, the NHC stuff is left untouched...
Although i had some free ports on the NHC connected controller, thus i plugged in an additional NIC directly connected to my HASS server. 
Now my HASS server has 1 nic in my home network `192.168.0.x/24` and another one in the NHC network `10.69.55.x/16`

This is the config in frigate to pick up the video stream (however, the audio is not yet working, still trying to figure out that one...):

```
cameras:
  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123qwe@10.69.55.228/rtsp/video.av?video=h264&hardware&audio=pcmu
          roles:
            - detect
            - record
            - audio
```
