### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [filipvh/hass-nhc2#5]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by filipvh** [comment]
I wouldn't mind a PR

**Comment by KTibow** [comment]
Here's a couple of questions:
- Packaged or independent? I made a combined GH action, but it's totally optional, however it means that it will constantly get better.
- Do you need auto-formatting? I made a bit of code that can auto-format your code, which makes it more maintainable. It's completely optional.

**Comment by filipvh** [comment]
@KTibow I've been thinking, but I'll pass.
Thanks for asking/proposing.
